/**
 * This file was generated by the JPA Modeler
 */
package Entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotBlank;

/**
 * @author Users
 */
@Entity
@IdClass(AssurancePK.class)
public class Assurance implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false, length = 15)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir une assurance")
    @Pattern(regexp = "Au tiers|Intermédiaire|Tous risques", message = "Erreur sur le choix de l'assurance.")
    private String packassurance;

    @Column(nullable = false, length = 30)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir un mode de parking")
    private String parking;

    @Column(nullable = false, length = 30)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir le mode d\'utilisation de votre véhicule")
    private String utilsationvoiture;

    @Column(nullable = false)
    @Basic(optional = false)
    private int kmmax;

    @Id
    @ManyToOne(targetEntity = Voiture.class)
    private Voiture voiture;

    @Id
    @ManyToOne(targetEntity = Utilisateur.class)
    private Utilisateur utilisateur;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackassurance() {
        return this.packassurance;
    }

    public void setPackassurance(String packassurance) {
        this.packassurance = packassurance;
    }

    public String getParking() {
        return this.parking;
    }

    public void setParking(String parking) {
        this.parking = parking;
    }

    public String getUtilsationvoiture() {
        return this.utilsationvoiture;
    }

    public void setUtilsationvoiture(String utilsationvoiture) {
        this.utilsationvoiture = utilsationvoiture;
    }

    public int getKmmax() {
        return this.kmmax;
    }

    public void setKmmax(int kmmax) {
        this.kmmax = kmmax;
    }

    public Voiture getVoiture() {
        return this.voiture;
    }

    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

}
