/**
 * This file was generated by the JPA Modeler
 */
package Entity;

import java.io.Serializable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

/**
 * @author Users
 */
@Entity
public class Utilisateur implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotBlank(message = "Ce champs est obligatoire")
    @Pattern(regexp = "Mr.|Mme.|Mlle.", message = "Vous ne pouvez choisir qu\'entre Mr. , Mme. ou Mlle.")
    @Column(nullable = false, length = 5)
    @Basic(optional = false)
    private String civilite;

    @NotBlank(message = "Vous devez saisir votre nom")
    @Length(min = 2, message = "Vous devez saisir au moins 2 caractères")
    @Column(nullable = false, length = 30)
    @Basic(optional = false)
    private String nom;

    @NotBlank(message = "Vous devez saisir votre prénom")
    @Length(min = 2, message = "Vous devez saisir au moins 2 caractères")
    @Column(nullable = false, length = 30)
    @Basic(optional = false)
    private String prenom;

    @NotBlank(message = "Vous devez saisir votre date de naissance (jj-mm-aaaa)")
    @Column(nullable = false)
    @Basic(optional = false)
    private String datenaissance;

    @NotBlank(message = "Vous devez saisir votre adresse")
    @Column(nullable = false, length = 100)
    @Basic(optional = false)
    private String adresse;

    @NotBlank(message = "Vous devez saisir votre ville")
    @Column(nullable = false, length = 50)
    @Basic(optional = false)
    private String ville;

    @NotBlank(message = "Vous devez saisir votre code postal")
    @Length(min = 3, max = 5, message = "Vous devez saisir un CP entre 3 et 5 caractères")
    @Column(nullable = false, length = 5)
    @Basic(optional = false)
    private String cp;

    @NotBlank(message = "Vous devez saisir votre email")
    @Email(message = "Vous devez saisir un email valide")
    @Column(nullable = false, length = 50)
    @Basic(optional = false)
    private String email;

    @NotBlank(message = "Vous devez saisir un identifiant")
    @Length(min = 5, message = "Vous devez saisir au moins 5 caractères")
    @Column(nullable = false, length = 15)
    @Basic(optional = false)
    private String identifiant;

    @NotBlank(message = "Vous devez saisir un mot de passe")
    @Column(nullable = false)
    @Basic(optional = false)
    private String motdepasse;

    public static String sha1(String input) throws NoSuchAlgorithmException {
        MessageDigest mDigest = MessageDigest.getInstance("SHA1");
        byte[] result = mDigest.digest(input.getBytes());
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < result.length; i++) {
            sb.append(Integer.toString((result[i] & 0xff) + 0x100, 16).substring(1));
        }

        return sb.toString();
    }

    /* ======= GET & SET ======= */
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCivilite() {
        return this.civilite;
    }

    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getDatenaissance() {
        return this.datenaissance;
    }

    public void setDatenaissance(String datenaissance) {
        this.datenaissance = datenaissance;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getVille() {
        return this.ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdentifiant() {
        return this.identifiant;
    }

    public void setIdentifiant(String identifiant) {
        this.identifiant = identifiant;
    }

    public String getMotdepasse() {
        return this.motdepasse;
    }

    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }

}
