/**
 * This file was generated by the JPA Modeler
 */
package Entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.hibernate.validator.constraints.NotBlank;

/**
 * @author Users
 */
@Entity
public class Voiture implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false, length = 15)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir une marque")
    private String marque;

    @Column(nullable = false, length = 15)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir un modele")
    private String modele;

    @Column(nullable = false, length = 25)
    @Basic(optional = false)
    @NotBlank(message = "Vous devez choisir une version")
    private String version;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMarque() {
        return this.marque;
    }

    public void setMarque(String marque) {
        this.marque = marque;
    }

    public String getModele() {
        return this.modele;
    }

    public void setModele(String modele) {
        this.modele = modele;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

}
